### ISSUE TITLE
Button debounce - is it possible

### ISSUE THREAD

**Issue by dsssssssss9** [MKleinSB/pxt-KY-040#2]
Hi

I am making start on coding a simple invaders type game using Callimatix 8x8 for display & KY-040 as a controller

I have noticed that when pressing the button on the encoder i tend to get multiple presses registered - for instance when i press the button on the encoder to fire my "missile" it will fire 2 or 3

I have tried doing a simple debounce routine in makecode but so far no luck

So yet another cheeky request - is it possible to have some sort of debounce built into the extension ?

Hope this is the right place for this sort of request - if not please let me know !

TTFN

**Comment by MKleinSB** [comment]
Yes, it should be possible. I will try it out this week.

**Comment by MKleinSB** [comment]
Seemes to work now!

**Comment by dsssssssss9** [comment]
HI

It appears that the extension now expects the switch to be on Pin2 ?
Any other pin doesn't work ?

Not the biggest problem in the world but is it possible to use a pin of the user's choice?

Sorry!!

**Comment by MKleinSB** [comment]
Puh!
Now it works with your Program.
Thanks and have fun. Feel free to ask for more.

Michael

**Comment by dsssssssss9** [comment]
Very Kind of You
Sorry to have troubled you

Really appreciate this

TTFN

Jason
