### ISSUE TITLE
Make:Code Extension Approval?

### ISSUE THREAD

**Issue by stefan-scott** [MKleinSB/pxt-KY-040#4]
Hello,

Thanks for sharing your work. I'm a teacher and have been fighting with a different rotary encoder extension on Make:Code for quite a while before following a trail to your extension, which just works.

For our students, it's a tiny bit nicer to be able to search the extension straight from Make:code rather than having to enter a repo URL. Would you consider submitting this extension for official approval? Alternatively, if you would prefer I could fork this repo and do the work of going through those steps. I'm not so experienced in this area, but I am sure I can figure it out. I drew up a little card for the extension too.

![icon](https://user-images.githubusercontent.com/14060526/232671103-8b150263-9132-453f-bd33-44867f5f11a6.png)

**Comment by MKleinSB** [comment]
Hello,
feel free to use it and to let approve it. The image is quite nice!

Michael
